apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-generator
  labels:
    app: image-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-generator
  template:
    metadata:
      labels:
        app: image-generator
    spec:
      containers:
      - name: image-generator
        image: tu_usuario/image-generator:latest  # Reemplaza con tu imagen real
        ports:
        - containerPort: 8080  # Ajusta si usas otro puerto
