apiVersion: v1
kind: Service
metadata:
  name: image-generator
spec:
  selector:
    app: image-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Debe coincidir con el containerPort del Deployment
  type: LoadBalancer
